YLT address is now configurable
Webperf-se/webperf_core pull request #37
Opened 2021-01-07 10:57 UTC by marcusosterberg

Closes #36

2021-01-08 23:22 UTC, marcusosterberg commented
After some testing there is apparent that websites that are unable to be tested on the local instances still can be tested on the online edition of YLT. Therefore the script should first test using the local version and afterwards use the public URL.

2021-01-13 19:26 UTC, flowertwig-org commented on tests/frontend_quality_yellow_lab_tools.py
> +	r = requests.post('{}/api/runs'.format(ylt_server_address), data = {'url':url, "waitForResponse":'true', 'device': device})
```suggestion
	r = requests.post('{0}/api/runs'.format(ylt_server_address), data = {'url':url, "waitForResponse":'true', 'device': device})
```

2021-01-13 19:28 UTC, flowertwig-org requested changes

2021-01-13 19:28 UTC, flowertwig-org commented on tests/frontend_quality_yellow_lab_tools.py
> +	r = requests.post('{}/api/runs'.format(ylt_server_address), data = {'url':url, "waitForResponse":'true', 'device': device})
@marcusosterberg  Can we change it to the suggested version? If yes, I will approve it with that change :)

2021-07-03 17:21 UTC, closed without merging